networks:
    app-network:

volumes:
  db-data:

services:
  app:
    image: tech-app
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/php/memory.ini:/usr/local/etc/php/conf.d/99-memory.ini
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  queue:
    image: tech-app
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/php/memory.ini:/usr/local/etc/php/conf.d/99-memory.ini
    networks:
      - app-network
    depends_on:
      - database
      - app
    command: /bin/sh -c "php artisan queue:work"

